server:
  port: 8050
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
zuul:
  routes:
    app-a:
      path: /user/**
      serviceId: consumer-client
    app-sidecar: #通过 sidecar 调用 nodejs 的服务
      path: /sidecar/**
      serviceId: sidecar
#  prefix: /prefix
#  strip-prefix: true
