server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
spring:
  application:
    name: sidecar
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json
